use crate::{
    AaAutomationBenchSource, AaCritPtSource, AaEnterpriseOpsGymSource, AaGdpvalV2Source,
    AaItBenchSource, AaOmniscienceSource, AgcBenchSource, ArcAgiSource, ArtificialAnalysisSource,
    BfclSource, ContextArenaSource, DeepSweV11Source, EqBenchCreativeWritingSource,
    EqBenchJudgemarkSource, FactoryCodeReviewSource, GsoSource, HilBenchSource,
    LiveCodeBenchSource, LmArenaSource, McpAtlasSource, OpenRouterSource, OverridesSource,
    SonarSource, Source, SweAtlasQnaSource, SweAtlasRefactoringSource, SweAtlasTestWritingSource,
    SweBenchProSource, SweBenchSource, SweRebenchSource, TerminalBench21Source,
    TerminalBenchSource,
};

pub fn registry() -> Vec<Box<dyn Source>> {
    vec![
        Box::new(OpenRouterSource),
        Box::new(LmArenaSource),
        Box::new(ArtificialAnalysisSource),
        Box::new(AaGdpvalV2Source),
        Box::new(AaCritPtSource),
        Box::new(AaOmniscienceSource),
        Box::new(AaEnterpriseOpsGymSource),
        Box::new(AaAutomationBenchSource),
        Box::new(AaItBenchSource),
        Box::new(SweBenchSource),
        Box::new(SweBenchProSource),
        Box::new(SweAtlasQnaSource),
        Box::new(SweAtlasTestWritingSource),
        Box::new(SweAtlasRefactoringSource),
        Box::new(SweRebenchSource),
        Box::new(LiveCodeBenchSource),
        Box::new(GsoSource),
        Box::new(BfclSource),
        Box::new(EqBenchCreativeWritingSource),
        Box::new(EqBenchJudgemarkSource),
        Box::new(AgcBenchSource),
        Box::new(FactoryCodeReviewSource),
        Box::new(ContextArenaSource),
        Box::new(DeepSweV11Source),
        Box::new(TerminalBenchSource),
        Box::new(TerminalBench21Source),
        Box::new(HilBenchSource),
        Box::new(SonarSource),
        Box::new(McpAtlasSource),
        Box::new(ArcAgiSource),
        Box::new(OverridesSource::default()),
    ]
}
