use std::fmt::Write;

use crate::Scoreboard;

use super::{html_escape, layout};

pub fn render_index(scoreboard: &Scoreboard) -> String {
    let mut body = String::new();

    // Mode toggle. Long-form label collapses to "adjusted" on mobile via CSS.
    body.push_str(
        r#"<div class="mode-toggle" role="radiogroup" aria-label="Score mode">
  <button type="button" data-mode-value="raw" aria-pressed="true">raw</button>
  <button type="button" data-mode-value="adjusted" aria-pressed="false"><span class="mode-long">adjusted for review opportunity-cost</span><span class="mode-short">adjusted</span></button>
</div>"#,
    );

    body.push_str(&render_hero(scoreboard));

    body.push_str(SCORING_PANEL);

    body.push_str(&render_leaderboard(scoreboard));

    // Footer
    write!(
        body,
        r#"<footer>generated by {generator} · {generated_at} · <a href="about.html">about</a> · <a href="scoreboard.toml">api</a></footer>"#,
        generator = html_escape(&scoreboard.generator),
        generated_at = html_escape(&scoreboard.generated_at),
    )
    .unwrap();

    layout("ipbr-rank · live llm coding-role score", scoreboard, &body)
}

fn render_hero(scoreboard: &Scoreboard) -> String {
    let mut html = String::from("<section class=\"hero\" id=\"hero\">");
    for (role_id, role_label, raw_extractor, adj_extractor) in role_specs() {
        html.push_str(&format!(
            "<div class=\"role {role_id}\"><div class=\"role-head\">[ {role_label} ]</div>"
        ));
        let mut ranked: Vec<&ipbr_core::ModelRecord> = scoreboard.models.iter().collect();
        ranked.sort_by(|left, right| {
            raw_extractor(right)
                .partial_cmp(&raw_extractor(left))
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        for (idx, model) in ranked.iter().take(3).enumerate() {
            let pos = idx + 1;
            let row_class = if idx == 0 { "row top" } else { "row" };
            let raw = raw_extractor(model);
            let adj = adj_extractor(model);
            html.push_str(&format!(
                r#"<div class="{row_class}"><span class="pos">{pos}</span><span class="name">{name}</span><span class="score"><span class="score-raw" data-tier="{raw_tier}">{raw:.1}</span><span class="score-adjusted" data-tier="{adj_tier}">{adj:.1}</span></span></div>"#,
                name = html_escape(&model.display_name),
                raw_tier = score_tier(raw),
                adj_tier = score_tier(adj),
            ));
        }
        html.push_str("</div>");
    }
    html.push_str("</section>");
    html
}

fn score_tier(score: f64) -> &'static str {
    if score >= 70.0 {
        "high"
    } else if score >= 50.0 {
        "mid"
    } else {
        "low"
    }
}

type RoleExtractor = fn(&ipbr_core::ModelRecord) -> f64;

fn role_specs() -> [(&'static str, &'static str, RoleExtractor, RoleExtractor); 4] {
    [
        ("idea",   "idea",   |m| m.scores.i_raw, |m| m.scores.i_adj),
        ("plan",   "plan",   |m| m.scores.p_raw, |m| m.scores.p_adj),
        ("build",  "build",  |m| m.scores.b_raw, |m| m.scores.b_adj),
        ("review", "review", |m| m.scores.r,     |m| m.scores.r),
    ]
}

fn render_leaderboard(scoreboard: &Scoreboard) -> String {
    let mut models: Vec<&ipbr_core::ModelRecord> = scoreboard.models.iter().collect();
    // Default order: descending by build raw (most-asked role for "best coder").
    models.sort_by(|left, right| {
        right
            .scores
            .b_raw
            .partial_cmp(&left.scores.b_raw)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| left.canonical_id.cmp(&right.canonical_id))
    });

    let mut vendors: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    for model in &models {
        vendors.insert(model.vendor.as_str());
    }

    let mut html = String::from(
        r##"<section id="leaderboard"><div class="toolbar"><input data-filter-input="#leaderboard-table" type="search" placeholder="filter models, vendors, sources"><div class="vendor-chips">"##,
    );
    html.push_str(r#"<button type="button" data-vendor="" class="active">all</button>"#);
    for vendor in &vendors {
        html.push_str(&format!(
            r#"<button type="button" data-vendor="{v}">{v}</button>"#,
            v = html_escape(vendor),
        ));
    }
    html.push_str(r#"</div></div><div class="lb-scroll"><table class="leaderboard" id="leaderboard-table"><thead><tr>"#);
    html.push_str(r#"<th data-sort="model"><button type="button" class="sort">model</button></th>"#);
    html.push_str(r#"<th data-sort="vendor"><button type="button" class="sort">vendor</button></th>"#);

    // Score columns — emit raw and adjusted as separate <th>s; CSS hides one set per mode.
    // The build column is the default sort, marked active on initial render.
    for (label, key) in [("idea", "i"), ("plan", "p"), ("build", "b")] {
        let active_attr = if key == "b" { r#" data-sort-active="desc""# } else { "" };
        html.push_str(&format!(
            r#"<th class="num score-raw" data-sort="{key}"{active_attr}><button type="button" class="sort">{label}</button></th>"#
        ));
        html.push_str(&format!(
            r#"<th class="num score-adjusted" data-sort="{key}"{active_attr}><button type="button" class="sort">{label}</button></th>"#
        ));
    }
    html.push_str(r#"<th class="num" data-sort="r"><button type="button" class="sort">review</button></th>"#);
    html.push_str(r#"<th></th></tr></thead><tbody>"#);

    for model in &models {
        html.push_str(&render_row(scoreboard, model));
    }

    html.push_str("</tbody></table></div></section>");
    html
}

fn render_row(scoreboard: &Scoreboard, model: &ipbr_core::ModelRecord) -> String {
    let mut html = String::new();
    let s = &model.scores;
    let id = html_escape(&model.canonical_id);
    let vendor = html_escape(model.vendor.as_str());
    let name = html_escape(&model.display_name);

    write!(
        html,
        r#"<tr class="row" id="{id}" data-vendor="{vendor}" data-sort-model="{name_lc}" data-sort-vendor="{vendor}" data-sort-i="{i:.4}" data-sort-p="{p:.4}" data-sort-b="{b:.4}" data-sort-r="{r:.4}"><td>{name}</td><td>{vendor}</td>"#,
        name_lc = name.to_lowercase(),
        i = s.i_raw,
        p = s.p_raw,
        b = s.b_raw,
        r = s.r,
    )
    .unwrap();

    for (raw, adj) in [(s.i_raw, s.i_adj), (s.p_raw, s.p_adj), (s.b_raw, s.b_adj)] {
        write!(
            html,
            r#"<td class="num score-raw" data-tier="{raw_tier}">{raw:.1}</td><td class="num score-adjusted" data-tier="{adj_tier}">{adj:.1}</td>"#,
            raw_tier = score_tier(raw),
            adj_tier = score_tier(adj),
        )
        .unwrap();
    }
    write!(
        html,
        r#"<td class="num" data-tier="{r_tier}">{r:.1}</td><td class="expand-toggle" role="button" aria-label="expand">▸</td></tr>"#,
        r = s.r,
        r_tier = score_tier(s.r),
    )
    .unwrap();

    // Expansion row
    write!(
        html,
        r#"<tr class="expand" data-row="{id}"><td colspan="10"><div class="expand-inner"><section class="exp-block"><h4>group breakdown</h4>{groups}</section><section class="exp-block"><h4>metrics</h4>{metrics}</section><section class="exp-block exp-meta"><span class="exp-meta-label">sources</span> {sources}<span class="exp-meta-label">missing</span> {missing}</section></div></td></tr>"#,
        groups = render_group_table(scoreboard, model),
        metrics = render_metric_table(scoreboard, model),
        sources = render_source_pills(scoreboard, model),
        missing = render_missing_pills(model),
    )
    .unwrap();

    html
}

fn rank_for(scoreboard: &Scoreboard, canonical_id: &str, lookup: impl Fn(&ipbr_core::ModelRecord) -> Option<f64>) -> Option<(usize, usize)> {
    let mut scored: Vec<(f64, &str)> = scoreboard
        .models
        .iter()
        .filter_map(|m| lookup(m).map(|v| (v, m.canonical_id.as_str())))
        .collect();
    if scored.is_empty() {
        return None;
    }
    scored.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));
    let pos = scored.iter().position(|(_, id)| *id == canonical_id)?;
    Some((pos + 1, scored.len()))
}

fn rank_bar_width(rank: Option<(usize, usize)>) -> f64 {
    match rank {
        Some((p, total)) if total > 0 => ((total - p + 1) as f64) / (total as f64) * 100.0,
        _ => 0.0,
    }
}

fn rank_text(rank: Option<(usize, usize)>) -> (String, &'static str) {
    match rank {
        Some((1, total)) => (format!("1 / {total}"), "exp-rank top"),
        Some((p, total)) => (format!("{p} / {total}"), "exp-rank"),
        None => (String::from("—"), "exp-rank"),
    }
}

fn render_group_table(scoreboard: &Scoreboard, model: &ipbr_core::ModelRecord) -> String {
    if model.groups.is_empty() {
        return r#"<div class="muted">no group scores</div>"#.to_string();
    }
    let mut html = String::from(r#"<div class="exp-table">"#);
    for (group, score) in &model.groups {
        let group_owned = group.clone();
        let rank = rank_for(scoreboard, &model.canonical_id, |m| m.groups.get(&group_owned).copied());
        let bar_width = rank_bar_width(rank);
        let (rank_label, rank_class) = rank_text(rank);
        html.push_str(&format!(
            r#"<span class="exp-label">{label}</span><span class="exp-bar"><span class="exp-bar-fill" style="width:{bar_width:.0}%"></span></span><span class="exp-value" data-tier="{tier}">{score:.1}</span><span class="{rank_class}">{rank_label}</span>"#,
            label = html_escape(group),
            tier = score_tier(*score),
        ));
    }
    html.push_str("</div>");
    html
}

fn render_metric_table(scoreboard: &Scoreboard, model: &ipbr_core::ModelRecord) -> String {
    if model.metrics.is_empty() {
        return r#"<div class="muted">no metrics</div>"#.to_string();
    }
    let mut html = String::from(r#"<div class="exp-table">"#);
    for (key, value) in &model.metrics {
        let marker = if model.synthesized.contains_key(key) { "*" } else { "" };
        let key_owned = key.clone();
        let rank = rank_for(scoreboard, &model.canonical_id, |m| m.metrics.get(&key_owned).copied());
        let bar_width = rank_bar_width(rank);
        let (rank_label, rank_class) = rank_text(rank);
        html.push_str(&format!(
            r#"<span class="exp-label">{key}{marker}</span><span class="exp-bar"><span class="exp-bar-fill" style="width:{bar_width:.0}%"></span></span><span class="exp-value" data-tier="{tier}">{value:.1}</span><span class="{rank_class}">{rank_label}</span>"#,
            key = html_escape(key),
            tier = score_tier(*value),
        ));
    }
    html.push_str("</div>");
    html
}

fn render_source_pills(scoreboard: &Scoreboard, model: &ipbr_core::ModelRecord) -> String {
    let synthesized_sources: std::collections::BTreeSet<&String> = model
        .synthesized
        .values()
        .map(|p| &p.source_id)
        .collect();
    let all_sources: std::collections::BTreeSet<&String> = model
        .sources
        .iter()
        .chain(synthesized_sources.iter().copied())
        .collect();
    if all_sources.is_empty() {
        return r#"<div class="muted">no sources</div>"#.to_string();
    }
    let mut html = String::new();
    for source in &all_sources {
        let synthesized_only = !model.sources.contains(*source);
        let suffix = if synthesized_only { "*" } else { "" };
        let status = scoreboard
            .source_summary
            .get(*source)
            .map(|s| s.status.as_str())
            .unwrap_or("unknown");
        html.push_str(&format!(
            r#"<span class="pill" title="{status}">{name}{suffix}</span>"#,
            name = html_escape(source),
            status = html_escape(status),
        ));
    }
    html
}

fn render_missing_pills(model: &ipbr_core::ModelRecord) -> String {
    if model.missing.metrics.is_empty() {
        return r#"<span class="muted">none</span>"#.to_string();
    }
    let mut html = String::new();
    for metric in &model.missing.metrics {
        html.push_str(&format!(
            r#"<span class="pill">{m}</span>"#,
            m = html_escape(metric),
        ));
    }
    html
}

const SCORING_PANEL: &str = r##"<details class="scoring" id="scoring">
<summary>how scoring works</summary>
<div class="scoring-body">
<p>Each model gets four role scores from public benchmarks. <strong>Idea</strong> measures open-ended creativity. <strong>Plan</strong> measures structured reasoning, function-calling, and multi-step decomposition. <strong>Build</strong> measures implementation skill — SWE-bench, LiveCodeBench, terminal tasks. <strong>Review</strong> measures preference judgment.</p>

<h3>raw vs adjusted</h3>
<p>The <em>raw</em> score is the benchmark composite, normalized to 0-100. The <em>adjusted</em> score subtracts a <strong>reviewer-reservation</strong> penalty: when a vendor's models dominate Review, that lead gets discounted from their Idea, Plan, and Build scores so vendors can't game their own preference evaluations.</p>

<p>Penalty coefficients differ by role: Build is penalized hardest (0.32), Plan moderately (0.18), Idea lightly (0.08). Review is never adjusted — it is the source of the penalty.</p>

<h3>missing data</h3>
<p>If a model is missing some metrics within a group, the group score is computed from the present metrics if at least 70% of the group weight is covered. Below that threshold, the score shrinks toward 50 proportional to the missing weight.</p>

<p><a href="about.html">Full math, role definitions, and source list →</a></p>
</div>
</details>"##;
