use std::collections::BTreeMap;
use std::fmt::Write;

use crate::Scoreboard;

use super::detail::render_detail;
use super::radar::{RadarScale, RadarScales, RadarSlice, render_radar};
use super::{html_escape, layout};

pub fn render_index(scoreboard: &Scoreboard) -> String {
    let mut body = String::new();

    let radar_scales = top10_axis_scales(scoreboard);
    let ranks = RoleRanks::build(scoreboard);

    body.push_str(&render_hero(scoreboard, radar_scales, &ranks));

    body.push_str(SCORING_PANEL);

    body.push_str(
        r#"<p class="provisional-note"><span aria-hidden="true">*</span> provisional — direct-evidence requirements not met</p>"#,
    );

    body.push_str(&render_leaderboard(scoreboard, &ranks, radar_scales));

    write!(
        body,
        r#"<footer>generated by {generator} · {generated_at} · <a href="about.html">about</a> · <a href="scoreboard.toml">api</a></footer>"#,
        generator = html_escape(&scoreboard.generator),
        generated_at = html_escape(&scoreboard.generated_at),
    )
    .unwrap();

    layout("ipbr · live llm coding scoreboard", &body)
}

fn render_hero(scoreboard: &Scoreboard, radar_scales: RadarScales, ranks: &RoleRanks) -> String {
    let evidence = scoreboard.coefficients.evidence.clone().unwrap_or_default();
    let top3: Vec<&ipbr_core::ModelRecord> =
        dense_ranked_models(scoreboard.models.iter().collect(), composite)
            .into_iter()
            .take(3)
            .map(|(_, model)| model)
            .collect();

    let radar_slices: Vec<RadarSlice> = top3
        .iter()
        .enumerate()
        .map(|(idx, model)| RadarSlice {
            idea: model.scores.i_raw,
            plan: model.scores.p_raw,
            build: model.scores.b_raw,
            review: model.scores.r,
            class: rank_class(idx),
            label: Some(model.display_name.as_str()),
            provisional: ipbr_core::balanced_is_provisional(model, &evidence),
        })
        .rev() // draw rank-3 first so rank-1 sits on top
        .collect();
    let radar_svg = render_radar(&radar_slices, radar_scales);

    let mut legend = String::from(r#"<ul class="hero-radar-legend">"#);
    for (idx, model) in top3.iter().enumerate() {
        write!(
            legend,
            r#"<li><span class="legend-dot {cls}" aria-hidden="true"></span><span class="legend-name">{name}</span></li>"#,
            cls = rank_class(idx),
            name = html_escape(&model.display_name),
        )
        .unwrap();
    }
    legend.push_str("</ul>");

    let leaders = render_leaders(scoreboard, ranks);

    format!(
        r#"<section class="hero" id="hero"><div class="hero-head"><p class="hero-tagline"><span class="beat beat-lead">Models drift.</span> <span class="beat">Evidence accumulates.</span> <span class="beat beat-final">Ranks update.</span></p><p class="hero-status"><span class="hero-stat"><span class="live-dot" aria-hidden="true"></span><span class="live-label">live</span></span><span class="hero-stat">refreshed <time datetime="{generated_at}" data-local-time>{generated_at}</time></span><span class="hero-stat">{sources} sources</span><span class="hero-stat">{models} models</span></p></div><div class="hero-body"><div class="hero-radar-wrap">{radar_svg}{legend}</div><div class="hero-leaders">{leaders}</div></div></section>"#,
        generated_at = html_escape(&scoreboard.generated_at),
        sources = scoreboard.source_summary.len(),
        models = scoreboard.models.len(),
    )
}

fn render_leaders(scoreboard: &Scoreboard, ranks: &RoleRanks) -> String {
    let mut html =
        String::from(r#"<h3 class="leaders-title">ranked leaders</h3><div class="leaders-grid">"#);
    for (role, spec) in role_specs().into_iter().enumerate() {
        let ranked = dense_ranked_models(scoreboard.models.iter().collect(), spec.from_record);
        write!(
            html,
            r#"<div class="role {role_id}"><div class="role-head">[ {label} ]</div><ol class="role-list">"#,
            role_id = spec.id,
            label = spec.label,
        )
        .unwrap();
        for (pos, model) in ranked.iter().take(3) {
            let row_class = if *pos == 1 { "row top" } else { "row" };
            let value = (spec.from_record)(model);
            // The chip trails the name here — a leader's movement is about the
            // model, not about the number it happens to sit at.
            let delta = render_rank_delta(ranks.delta(&model.canonical_id, role));
            let score = render_leader_score(value, role_is_provisional(model, spec.evidence_key));
            write!(
                html,
                r#"<li class="{row_class}"><span class="pos">{pos}</span><span class="name-wrap"><span class="name">{name}</span>{delta}</span><span class="score" data-tier="{tier}">{score}</span></li>"#,
                name = html_escape(&model.display_name),
                tier = score_tier(value),
            )
            .unwrap();
        }
        html.push_str("</ol></div>");
    }
    html.push_str("</div>");
    html
}

pub(super) fn composite(model: &ipbr_core::ModelRecord) -> f64 {
    let s = &model.scores;
    (s.i_raw + s.p_raw + s.b_raw + s.r) / 4.0
}

const RADAR_REFERENCE_COHORT: usize = 10;

/// Fixes each axis's [min, max] to the spread of the top-10 balanced-score
/// models, so the hero's three shapes share one reference frame instead of each
/// self-normalizing to its own. The expanded row's mini radar draws against the
/// same frame, keeping every radar on the page comparable.
pub(super) fn top10_axis_scales(scoreboard: &Scoreboard) -> RadarScales {
    let top10: Vec<&ipbr_core::ModelRecord> =
        dense_ranked_models(scoreboard.models.iter().collect(), composite)
            .into_iter()
            .take(RADAR_REFERENCE_COHORT)
            .map(|(_, model)| model)
            .collect();

    let axis_range = |get: fn(&ipbr_core::RoleScores) -> f64| -> (f64, f64) {
        let mut min = f64::INFINITY;
        let mut max = f64::NEG_INFINITY;
        for model in &top10 {
            let value = get(&model.scores);
            min = min.min(value);
            max = max.max(value);
        }
        (min, max)
    };

    let (idea_min, idea_max) = axis_range(|s| s.i_raw);
    let (plan_min, plan_max) = axis_range(|s| s.p_raw);
    let (build_min, build_max) = axis_range(|s| s.b_raw);
    let (review_min, review_max) = axis_range(|s| s.r);

    RadarScales {
        idea: RadarScale::from_range(idea_min, idea_max),
        plan: RadarScale::from_range(plan_min, plan_max),
        build: RadarScale::from_range(build_min, build_max),
        review: RadarScale::from_range(review_min, review_max),
    }
}

/// Dense ranks aligned with the one-decimal score display: values that round
/// to the same displayed tenth share a rank, and the next distinct score gets
/// the next integer (1, 1, 2 rather than 1, 2, 3).
fn display_score_key(value: f64) -> String {
    format!("{value:.1}")
}

fn dense_ranked_models(
    mut models: Vec<&ipbr_core::ModelRecord>,
    score: fn(&ipbr_core::ModelRecord) -> f64,
) -> Vec<(usize, &ipbr_core::ModelRecord)> {
    models.sort_by(|a, b| {
        score(b)
            .partial_cmp(&score(a))
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.canonical_id.cmp(&b.canonical_id))
    });
    let mut dense_rank = 0;
    let mut previous: Option<String> = None;
    models
        .into_iter()
        .map(|model| {
            let value = score(model);
            let display_key = display_score_key(value);
            if previous.as_ref() != Some(&display_key) {
                dense_rank += 1;
                previous = Some(display_key);
            }
            (dense_rank, model)
        })
        .collect()
}

fn role_is_provisional(model: &ipbr_core::ModelRecord, role: &str) -> bool {
    model
        .evidence
        .roles
        .get(role)
        .is_some_and(|coverage| coverage.provisional)
}

fn rank_class(rank: usize) -> &'static str {
    match rank {
        0 => "rank-1",
        1 => "rank-2",
        _ => "rank-3",
    }
}

pub(super) fn score_tier(score: f64) -> &'static str {
    if score >= 70.0 {
        "high"
    } else if score >= 50.0 {
        "mid"
    } else {
        "low"
    }
}

const BAR_REFERENCE_COHORT: usize = 10;
const BAR_OPACITY_FLOOR: f64 = 0.2;

/// Per-axis `(min, max)` taken from the ten highest scorers on each axis, in
/// column order `[idea, plan, build, review]`. Score bars map across this
/// range so differences between the leaders are apparent instead of all
/// crowding the top of a 0–100 (or fixed-band) scale.
fn top10_bar_scales(scoreboard: &Scoreboard) -> [(f64, f64); 4] {
    let axis = |get: fn(&ipbr_core::RoleScores) -> f64| -> (f64, f64) {
        let mut values: Vec<f64> = scoreboard.models.iter().map(|m| get(&m.scores)).collect();
        values.sort_by(|a, b| b.partial_cmp(a).unwrap_or(std::cmp::Ordering::Equal));
        let top = &values[..values.len().min(BAR_REFERENCE_COHORT)];
        let max = top.first().copied().unwrap_or(0.0);
        let min = top.last().copied().unwrap_or(0.0);
        (min, max)
    };
    [
        axis(|s| s.i_raw),
        axis(|s| s.p_raw),
        axis(|s| s.b_raw),
        axis(|s| s.r),
    ]
}

/// Opacity for a cell's score bar within its axis's top-10 range, or `None`
/// (no bar) when the value falls below the axis's 10th-best score. The floor
/// keeps the 10th-place bar visibly distinct from the empty cells below it.
fn bar_opacity(value: f64, (min, max): (f64, f64)) -> Option<f64> {
    if value < min {
        return None;
    }
    let span = max - min;
    let t = if span > f64::EPSILON {
        ((value - min) / span).clamp(0.0, 1.0)
    } else {
        1.0
    };
    Some(BAR_OPACITY_FLOOR + t * (1.0 - BAR_OPACITY_FLOOR))
}

pub(super) struct RoleSpec {
    pub(super) id: &'static str,
    pub(super) label: &'static str,
    /// Column key on the leaderboard table (`data-sort`, `col-*` class).
    col: &'static str,
    /// Also the role's key in `final_score_weights`.
    pub(super) evidence_key: &'static str,
    pub(super) from_record: fn(&ipbr_core::ModelRecord) -> f64,
    from_scores: fn(&ipbr_core::RoleScores) -> f64,
}

/// The four roles in column order. Index into this array is the `role` index
/// used by [`RoleRanks`] and by the per-axis bar scales.
pub(super) fn role_specs() -> [RoleSpec; 4] {
    [
        RoleSpec {
            id: "idea",
            label: "idea",
            col: "i",
            evidence_key: "I_raw",
            from_record: |m| m.scores.i_raw,
            from_scores: |s| s.i_raw,
        },
        RoleSpec {
            id: "plan",
            label: "plan",
            col: "p",
            evidence_key: "P_raw",
            from_record: |m| m.scores.p_raw,
            from_scores: |s| s.p_raw,
        },
        RoleSpec {
            id: "build",
            label: "build",
            col: "b",
            evidence_key: "B_raw",
            from_record: |m| m.scores.b_raw,
            from_scores: |s| s.b_raw,
        },
        RoleSpec {
            id: "review",
            label: "review",
            col: "r",
            evidence_key: "R",
            from_record: |m| m.scores.r,
            from_scores: |s| s.r,
        },
    ]
}

/// Dense role ranks keyed by canonical_id, one map per role in `role_specs()`
/// order. Baseline ranks are ranked *within the baseline scoreboard's own
/// population*, so "up 2" means the model gained two places against the board
/// as it stood at the start of last week — models that have since arrived or
/// left are part of that movement, exactly as a reader would count it.
struct RoleRanks {
    current: [BTreeMap<String, usize>; 4],
    baseline: Option<[BTreeMap<String, usize>; 4]>,
}

impl RoleRanks {
    fn build(scoreboard: &Scoreboard) -> Self {
        let specs = role_specs();
        let current = std::array::from_fn(|role| {
            dense_ranks(
                scoreboard
                    .models
                    .iter()
                    .map(|model| {
                        (
                            model.canonical_id.as_str(),
                            (specs[role].from_record)(model),
                        )
                    })
                    .collect(),
            )
        });
        let baseline = scoreboard.prev_scores.as_ref().map(|prior| {
            std::array::from_fn(|role| {
                dense_ranks(
                    prior
                        .iter()
                        .map(|(id, scores)| (id.as_str(), (specs[role].from_scores)(scores)))
                        .collect(),
                )
            })
        });
        Self { current, baseline }
    }

    /// Places gained in `role` since the baseline; positive is upward. `None`
    /// when there is no baseline, or when the model was not on the baseline
    /// board (a new entry has nothing to have moved from).
    fn delta(&self, canonical_id: &str, role: usize) -> Option<i64> {
        let baseline = self.baseline.as_ref()?[role].get(canonical_id)?;
        let current = self.current[role].get(canonical_id)?;
        Some(*baseline as i64 - *current as i64)
    }
}

/// Dense-ranks `(canonical_id, score)` pairs, sharing a rank between scores
/// that render as the same tenth — the same tie rule as `dense_ranked_models`.
fn dense_ranks(mut scored: Vec<(&str, f64)>) -> BTreeMap<String, usize> {
    scored.sort_by(|a, b| {
        b.1.partial_cmp(&a.1)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.0.cmp(b.0))
    });
    let mut ranks = BTreeMap::new();
    let mut dense_rank = 0;
    let mut previous: Option<String> = None;
    for (id, score) in scored {
        let display_key = display_score_key(score);
        if previous.as_ref() != Some(&display_key) {
            dense_rank += 1;
            previous = Some(display_key);
        }
        ranks.insert(id.to_string(), dense_rank);
    }
    ranks
}

/// Renders a `▲2` / `▼1` chip for places gained or lost in a role since the
/// start of last week. Empty when the model held its rank, is new to the
/// board, or when no baseline snapshot was available.
fn render_rank_delta(delta: Option<i64>) -> String {
    let Some(delta) = delta.filter(|places| *places != 0) else {
        return String::new();
    };
    let (arrow, cls, dir) = if delta > 0 {
        ("▲", "delta delta-up", "up")
    } else {
        ("▼", "delta delta-down", "down")
    };
    let places = delta.abs();
    format!(
        r#"<span class="{cls}" aria-hidden="true" title="{places} {noun} {dir} since the start of last week">{arrow}{places}</span><span class="sr-only"> {dir} {places} {noun} since the start of last week</span>"#,
        noun = if places == 1 { "place" } else { "places" },
    )
}

fn render_leaderboard(
    scoreboard: &Scoreboard,
    ranks: &RoleRanks,
    radar_scales: RadarScales,
) -> String {
    let mut models: Vec<&ipbr_core::ModelRecord> = scoreboard.models.iter().collect();
    // Default order: build score. Individual role columns remain
    // independently sortable.
    models.sort_by(|left, right| {
        right
            .scores
            .b_raw
            .partial_cmp(&left.scores.b_raw)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| left.canonical_id.cmp(&right.canonical_id))
    });

    let mut vendors: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    for model in &models {
        vendors.insert(model.vendor.as_str());
    }

    let mut html = String::from(
        r##"<section id="leaderboard"><div class="toolbar"><div class="search-box"><svg class="search-icon" viewBox="0 0 16 16" aria-hidden="true" focusable="false"><circle cx="6.75" cy="6.75" r="4.75"></circle><line x1="10.4" y1="10.4" x2="14.5" y2="14.5"></line></svg><input data-filter-input="#leaderboard-table" type="search" placeholder="filter" aria-label="filter leaderboard by model or vendor"></div><div class="vendor-chips" role="group" aria-label="filter leaderboard by vendor">"##,
    );
    html.push_str(
        r#"<button type="button" data-vendor="" class="active" aria-pressed="true" aria-label="show all vendors">all</button>"#,
    );
    for vendor in &vendors {
        html.push_str(&format!(
            r#"<button type="button" data-vendor="{v}" aria-pressed="false" aria-label="show only {v} models">{v}</button>"#,
            v = html_escape(vendor),
        ));
    }
    html.push_str(r#"</div></div><div class="lb-scroll"><table class="leaderboard" id="leaderboard-table" data-active-col="b"><thead><tr>"#);
    html.push_str(r#"<th scope="col" class="rank" aria-label="rank">#</th>"#);
    html.push_str(
        r#"<th scope="col" data-sort="vendor" aria-sort="none"><button type="button" class="sort" aria-label="sort by vendor descending">vendor</button></th>"#,
    );
    html.push_str(
        r#"<th scope="col" data-sort="model" aria-sort="none"><button type="button" class="sort" aria-label="sort by model descending">model</button></th>"#,
    );

    // Score columns — build is the default sort.
    for spec in role_specs() {
        let (active_attr, aria_sort) = if spec.col == "b" {
            (r#" data-sort-active="desc""#, "descending")
        } else {
            ("", "none")
        };
        html.push_str(&format!(
            r#"<th scope="col" class="num" data-sort="{key}" aria-sort="{aria_sort}"{active_attr}><button type="button" class="sort" aria-label="sort by {label} score descending">{label}</button></th>"#,
            key = spec.col,
            label = spec.label,
        ));
    }
    html.push_str(r#"<th scope="col" aria-label="details"></th></tr></thead><tbody>"#);

    let bar_scales = top10_bar_scales(scoreboard);
    for (position, model) in models.iter().enumerate() {
        html.push_str(&render_row(
            scoreboard,
            model,
            bar_scales,
            ranks,
            radar_scales,
            position + 1,
        ));
    }

    html.push_str(r#"</tbody></table></div></section>"#);
    html
}

fn render_row(
    scoreboard: &Scoreboard,
    model: &ipbr_core::ModelRecord,
    bar_scales: [(f64, f64); 4],
    ranks: &RoleRanks,
    radar_scales: RadarScales,
    position: usize,
) -> String {
    let mut html = String::new();
    let s = &model.scores;
    let id = html_escape(&model.canonical_id);
    let vendor = html_escape(model.vendor.as_str());
    let name = html_escape(&model.display_name);

    write!(
        html,
        r#"<tr class="row" id="{id}" data-vendor="{vendor}" data-sort-model="{name_lc}" data-sort-vendor="{vendor}" data-sort-i="{i:.4}" data-sort-p="{p:.4}" data-sort-b="{b:.4}" data-sort-r="{r:.4}"><td class="rank" data-rank>{position}</td><td class="vendor">{vendor}</td><td class="model-name">{name}</td>"#,
        name_lc = name.to_lowercase(),
        i = s.i_raw,
        p = s.p_raw,
        b = s.b_raw,
        r = s.r,
    )
    .unwrap();

    for (role, spec) in role_specs().into_iter().enumerate() {
        let raw = (spec.from_record)(model);
        let provisional = role_is_provisional(model, spec.evidence_key);
        // The chip trails the score, which is the cell's subject.
        let delta = render_rank_delta(ranks.delta(&model.canonical_id, role));
        // No `--bar-op` below the axis's top-10 min → CSS falls back to opacity 0.
        let bar_style = match bar_opacity(raw, bar_scales[role]) {
            Some(op) => format!(r#" style="--bar-op:{op:.2}""#),
            None => String::new(),
        };
        write!(
            html,
            r#"<td class="num col-{colkey}" data-tier="{tier}" data-status="{status}"{bar_style}>{score}{delta}</td>"#,
            colkey = spec.col,
            tier = score_tier(raw),
            status = if provisional { "provisional" } else { "ranked" },
            score = render_score_value(raw, provisional),
        )
        .unwrap();
    }
    let details_id = format!("{id}-details");
    write!(
        html,
        r#"<td class="expand-toggle"><button type="button" aria-expanded="false" aria-controls="{details_id}" aria-label="show details for {name}" data-label-open="hide details for {name}" data-label-closed="show details for {name}">▸</button></td></tr>"#
    )
    .unwrap();

    write!(
        html,
        r#"<tr class="expand" id="{details_id}" data-row="{id}"><td colspan="8">{detail}</td></tr>"#,
        detail = render_detail(scoreboard, model, radar_scales),
    )
    .unwrap();

    html
}

fn render_score_value(value: f64, provisional: bool) -> String {
    if provisional {
        format!(
            r#"<span class="cell-score provisional-score"><em>{value:.1}</em><span class="status-marker" title="Provisional: direct-evidence requirements not met" aria-label="provisional">*</span></span>"#
        )
    } else {
        format!(r#"<span class="cell-score">{value:.1}</span>"#)
    }
}

fn render_leader_score(value: f64, provisional: bool) -> String {
    if provisional {
        format!(
            r#"<span class="provisional-score"><em>{value:.1}</em><span class="status-marker" title="Provisional: direct-evidence requirements not met" aria-label="provisional">*</span></span>"#
        )
    } else {
        format!("{value:.1}")
    }
}

const SCORING_PANEL: &str = r##"<details class="scoring" id="scoring">
<summary>how scoring works</summary>
<div class="scoring-body">
<p>Each model gets four capability proxies from public benchmarks. <strong>Idea</strong> includes EQ-Bench Creative Writing, preference, and novel-reasoning evidence. <strong>Plan</strong> measures structured reasoning, tool use, and multi-step execution. <strong>Build</strong> emphasizes software and terminal tasks. <strong>Review</strong> remains a proxy combining planning, building, search, and document evidence. Judgemark is diagnostic because judge discrimination is not code review, and no currently broad code-review benchmark is treated as direct evidence.</p>

<h3>scoring</h3>
<p>Ranked metrics use versioned fixed raw-score anchors and an asymptotic 0-100 logistic map. Every actual same-product observation counts fully, including vendor-automatic fallback with an explicit routing citation and cited vendor or system-card observations curated as overrides. Every scored value is a direct same-product measurement. Correlated metrics are collapsed by benchmark family, and no family may carry more than 30% of a role.</p>

<h3>missing data</h3>
<p>Capability is estimated from available same-product evidence; missing leaves reduce confidence rather than the point estimate. Eligibility is separate: broad core benchmarks establish current coverage, narrow supplemental benchmarks affect scores without making every missing row a penalty, and total-portfolio qualification still needs at least 35% direct core weight across three core families. Direct retired evidence can corroborate coverage history without entering the current score. Estimates that meet none of these gates remain in the same rank order but are italicized, starred, and shown with dotted radar outlines as provisional. The radar outline renders as ranked once three roles are ranked and the fourth carries at least 20% current direct coverage.</p>

<h3>configuration and diagnostics</h3>
<p>There is one record per served product. Vendor-automatic fallback is included, while separately named multi-agent or premium endpoints remain distinct. Where a benchmark exposes effort, the best available max/high-effort observation is preferred; benchmarks without effort metadata retain their reported configuration. Price, output speed, first-token latency, and advertised context are diagnostics only and never enter Idea, Plan, Build, or Review.</p>

<p><a href="about.html">Full math, role definitions, and source list →</a></p>
</div>
</details>"##;

#[cfg(test)]
mod tests {
    use super::{dense_ranks, display_score_key, render_rank_delta};

    #[test]
    fn dense_tie_key_matches_the_rendered_tenth() {
        assert_ne!(display_score_key(10.051), display_score_key(10.049));
        assert_eq!(display_score_key(10.04), display_score_key(9.96));
    }

    #[test]
    fn ranks_are_dense_and_shared_between_models_that_display_the_same_tenth() {
        let ranks = dense_ranks(vec![
            ("a", 90.0),
            ("b", 80.04), // displays as 80.0, so it ties with `c`
            ("c", 79.96),
            ("d", 70.0),
        ]);
        assert_eq!(ranks["a"], 1);
        assert_eq!(ranks["b"], 2);
        assert_eq!(ranks["c"], 2);
        assert_eq!(ranks["d"], 3, "the next distinct score takes the next rank");
    }

    #[test]
    fn rank_chips_read_as_places_gained_and_vanish_when_nothing_moved() {
        assert!(render_rank_delta(Some(2)).contains("▲2"));
        assert!(render_rank_delta(Some(2)).contains("2 places up"));
        assert!(render_rank_delta(Some(-1)).contains("▼1"));
        assert!(render_rank_delta(Some(-1)).contains("1 place down"));
        assert!(render_rank_delta(Some(0)).is_empty(), "held its rank");
        assert!(render_rank_delta(None).is_empty(), "no baseline rank");
    }
}
