use std::fmt::Write;

use crate::Scoreboard;

use super::radar::{RadarSlice, RadarVariant, render_radar};
use super::{html_escape, layout};

pub fn render_index(scoreboard: &Scoreboard) -> String {
    let mut body = String::new();

    body.push_str(&render_hero(scoreboard));

    body.push_str(SCORING_PANEL);

    body.push_str(&render_leaderboard(scoreboard));

    write!(
        body,
        r#"<footer>generated by {generator} · {generated_at} · <a href="about.html">about</a> · <a href="scoreboard.toml">api</a></footer>"#,
        generator = html_escape(&scoreboard.generator),
        generated_at = html_escape(&scoreboard.generated_at),
    )
    .unwrap();

    layout("ipbr · live llm coding scoreboard", scoreboard, &body)
}

fn render_hero(scoreboard: &Scoreboard) -> String {
    let mut by_composite: Vec<&ipbr_core::ModelRecord> = scoreboard.models.iter().collect();
    by_composite.sort_by(|a, b| {
        composite(b)
            .partial_cmp(&composite(a))
            .unwrap_or(std::cmp::Ordering::Equal)
    });
    let top3: Vec<&ipbr_core::ModelRecord> = by_composite.into_iter().take(3).collect();

    let radar_slices: Vec<RadarSlice> = top3
        .iter()
        .enumerate()
        .map(|(idx, model)| RadarSlice {
            idea: model.scores.i_raw,
            plan: model.scores.p_raw,
            build: model.scores.b_raw,
            review: model.scores.r,
            class: rank_class(idx),
            label: Some(model.display_name.as_str()),
        })
        .rev() // draw rank-3 first so rank-1 sits on top
        .collect();
    let radar_svg = render_radar(&radar_slices, RadarVariant::Hero);

    let mut legend = String::from(r#"<ul class="hero-radar-legend">"#);
    for (idx, model) in top3.iter().enumerate() {
        write!(
            legend,
            r#"<li><span class="legend-dot {cls}" aria-hidden="true"></span><span class="legend-name">{name}</span><span class="legend-score">{score:.1}</span></li>"#,
            cls = rank_class(idx),
            name = html_escape(&model.display_name),
            score = composite(model),
        )
        .unwrap();
    }
    legend.push_str("</ul>");

    let leaders = render_leaders(scoreboard);

    format!(
        r#"<section class="hero" id="hero"><div class="hero-head"><p class="hero-tagline"><span class="beat beat-lead">Models drift.</span> <span class="beat">Agents battle.</span> <span class="beat beat-final">Math decides.</span></p><p class="hero-status"><span class="live-dot" aria-hidden="true"></span><span class="live-label">live</span> · refreshed <time datetime="{generated_at}" data-local-time>{generated_at}</time> · {sources} sources · {models} models</p></div><div class="hero-body"><div class="hero-radar-wrap">{radar_svg}{legend}</div><div class="hero-leaders">{leaders}</div></div></section>"#,
        generated_at = html_escape(&scoreboard.generated_at),
        sources = scoreboard.source_summary.len(),
        models = scoreboard.models.len(),
    )
}

fn render_leaders(scoreboard: &Scoreboard) -> String {
    let mut html =
        String::from(r#"<h3 class="leaders-title">leaders now</h3><div class="leaders-grid">"#);
    for spec in role_specs() {
        let mut ranked: Vec<&ipbr_core::ModelRecord> = scoreboard.models.iter().collect();
        ranked.sort_by(|a, b| {
            (spec.from_record)(b)
                .partial_cmp(&(spec.from_record)(a))
                .unwrap_or(std::cmp::Ordering::Equal)
        });
        write!(
            html,
            r#"<div class="role {role_id}"><div class="role-head">[ {label} ]</div><ol class="role-list">"#,
            role_id = spec.id,
            label = spec.label,
        )
        .unwrap();
        for (idx, model) in ranked.iter().take(3).enumerate() {
            let pos = idx + 1;
            let row_class = if idx == 0 { "row top" } else { "row" };
            let score = (spec.from_record)(model);
            let prev = scoreboard
                .prev_scores
                .as_ref()
                .and_then(|map| map.get(&model.canonical_id))
                .map(spec.from_scores);
            let delta = render_delta(score, prev);
            write!(
                html,
                r#"<li class="{row_class}"><span class="pos">{pos}</span><span class="name">{name}</span><span class="score" data-tier="{tier}">{score:.1}</span>{delta}</li>"#,
                name = html_escape(&model.display_name),
                tier = score_tier(score),
            )
            .unwrap();
        }
        html.push_str("</ol></div>");
    }
    html.push_str("</div>");
    html
}

fn composite(model: &ipbr_core::ModelRecord) -> f64 {
    let s = &model.scores;
    (s.i_raw + s.p_raw + s.b_raw + s.r) / 4.0
}

fn rank_class(rank: usize) -> &'static str {
    match rank {
        0 => "rank-1",
        1 => "rank-2",
        _ => "rank-3",
    }
}

fn score_tier(score: f64) -> &'static str {
    if score >= 70.0 {
        "high"
    } else if score >= 50.0 {
        "mid"
    } else {
        "low"
    }
}

struct RoleSpec {
    id: &'static str,
    label: &'static str,
    from_record: fn(&ipbr_core::ModelRecord) -> f64,
    from_scores: fn(&ipbr_core::RoleScores) -> f64,
}

fn role_specs() -> [RoleSpec; 4] {
    [
        RoleSpec {
            id: "idea",
            label: "idea",
            from_record: |m| m.scores.i_raw,
            from_scores: |s| s.i_raw,
        },
        RoleSpec {
            id: "plan",
            label: "plan",
            from_record: |m| m.scores.p_raw,
            from_scores: |s| s.p_raw,
        },
        RoleSpec {
            id: "build",
            label: "build",
            from_record: |m| m.scores.b_raw,
            from_scores: |s| s.b_raw,
        },
        RoleSpec {
            id: "review",
            label: "review",
            from_record: |m| m.scores.r,
            from_scores: |s| s.r,
        },
    ]
}

/// Renders a `▲+1.2` / `▼-0.8` chip when the prior score differs by ≥0.05.
/// Returns an empty string when there is no prior score or the change is
/// below the noise floor.
fn render_delta(current: f64, prev: Option<f64>) -> String {
    let Some(prev) = prev else {
        return String::new();
    };
    let delta = current - prev;
    if delta.abs() < 0.05 {
        return String::new();
    }
    let (arrow, cls, dir) = if delta > 0.0 {
        ("▲", "delta delta-up", "up")
    } else {
        ("▼", "delta delta-down", "down")
    };
    format!(
        r#"<span class="{cls}" aria-hidden="true">{arrow}{delta:+.1}</span><span class="sr-only"> {dir} {abs:.1} since last refresh</span>"#,
        abs = delta.abs(),
    )
}

fn render_leaderboard(scoreboard: &Scoreboard) -> String {
    let mut models: Vec<&ipbr_core::ModelRecord> = scoreboard.models.iter().collect();
    // Default order: descending by build raw (most-asked role for "best coder").
    models.sort_by(|left, right| {
        right
            .scores
            .b_raw
            .partial_cmp(&left.scores.b_raw)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| left.canonical_id.cmp(&right.canonical_id))
    });

    let mut vendors: std::collections::BTreeSet<&str> = std::collections::BTreeSet::new();
    for model in &models {
        vendors.insert(model.vendor.as_str());
    }

    let mut html = String::from(
        r##"<section id="leaderboard"><div class="toolbar"><input data-filter-input="#leaderboard-table" type="search" placeholder="filter by model or vendor"><div class="vendor-chips">"##,
    );
    html.push_str(r#"<button type="button" data-vendor="" class="active">all</button>"#);
    for vendor in &vendors {
        html.push_str(&format!(
            r#"<button type="button" data-vendor="{v}">{v}</button>"#,
            v = html_escape(vendor),
        ));
    }
    html.push_str(r#"</div></div><div class="lb-scroll"><table class="leaderboard" id="leaderboard-table"><thead><tr>"#);
    html.push_str(
        r#"<th data-sort="model"><button type="button" class="sort">model</button></th>"#,
    );
    html.push_str(
        r#"<th data-sort="vendor"><button type="button" class="sort">vendor</button></th>"#,
    );

    // Score columns — build is the default sort, marked active on initial render.
    for (label, key) in [("idea", "i"), ("plan", "p"), ("build", "b")] {
        let active_attr = if key == "b" {
            r#" data-sort-active="desc""#
        } else {
            ""
        };
        html.push_str(&format!(
            r#"<th class="num" data-sort="{key}"{active_attr}><button type="button" class="sort">{label}</button></th>"#
        ));
    }
    html.push_str(
        r#"<th class="num" data-sort="r"><button type="button" class="sort">review</button></th>"#,
    );
    html.push_str(r#"<th></th></tr></thead><tbody>"#);

    for model in &models {
        html.push_str(&render_row(scoreboard, model));
    }

    html.push_str("</tbody></table></div></section>");
    html
}

fn render_row(scoreboard: &Scoreboard, model: &ipbr_core::ModelRecord) -> String {
    let mut html = String::new();
    let s = &model.scores;
    let id = html_escape(&model.canonical_id);
    let vendor = html_escape(model.vendor.as_str());
    let name = html_escape(&model.display_name);
    let prev = scoreboard
        .prev_scores
        .as_ref()
        .and_then(|map| map.get(&model.canonical_id));

    write!(
        html,
        r#"<tr class="row" id="{id}" data-vendor="{vendor}" data-sort-model="{name_lc}" data-sort-vendor="{vendor}" data-sort-i="{i:.4}" data-sort-p="{p:.4}" data-sort-b="{b:.4}" data-sort-r="{r:.4}"><td>{name}</td><td>{vendor}</td>"#,
        name_lc = name.to_lowercase(),
        i = s.i_raw,
        p = s.p_raw,
        b = s.b_raw,
        r = s.r,
    )
    .unwrap();

    type ScoreAccessor = fn(&ipbr_core::RoleScores) -> f64;
    let columns: [(f64, ScoreAccessor); 4] = [
        (s.i_raw, |x| x.i_raw),
        (s.p_raw, |x| x.p_raw),
        (s.b_raw, |x| x.b_raw),
        (s.r, |x| x.r),
    ];
    for (raw, accessor) in columns {
        let prev_score = prev.map(accessor);
        let delta = render_delta(raw, prev_score);
        write!(
            html,
            r#"<td class="num" data-tier="{tier}"><span class="cell-score">{raw:.1}</span>{delta}</td>"#,
            tier = score_tier(raw),
        )
        .unwrap();
    }
    write!(
        html,
        r#"<td class="expand-toggle" role="button" aria-label="expand">▸</td></tr>"#
    )
    .unwrap();

    let mini_radar = render_radar(
        &[RadarSlice {
            idea: s.i_raw,
            plan: s.p_raw,
            build: s.b_raw,
            review: s.r,
            class: "solo",
            label: Some(model.display_name.as_str()),
        }],
        RadarVariant::Mini,
    );

    write!(
        html,
        r#"<tr class="expand" data-row="{id}"><td colspan="10"><div class="expand-inner"><div class="exp-radar">{mini_radar}</div><div class="exp-tables"><section class="exp-block"><h4>group breakdown</h4>{groups}</section><section class="exp-block"><h4>metrics</h4>{metrics}</section><section class="exp-block exp-meta"><span class="exp-meta-label">sources</span> {sources}<span class="exp-meta-label">missing</span> {missing}</section></div></div></td></tr>"#,
        groups = render_group_table(scoreboard, model),
        metrics = render_metric_table(scoreboard, model),
        sources = render_source_pills(scoreboard, model),
        missing = render_missing_pills(model),
    )
    .unwrap();

    html
}

fn rank_for(
    scoreboard: &Scoreboard,
    canonical_id: &str,
    lookup: impl Fn(&ipbr_core::ModelRecord) -> Option<f64>,
) -> Option<(usize, usize)> {
    let mut scored: Vec<(f64, &str)> = scoreboard
        .models
        .iter()
        .filter_map(|m| lookup(m).map(|v| (v, m.canonical_id.as_str())))
        .collect();
    if scored.is_empty() {
        return None;
    }
    scored.sort_by(|a, b| b.0.partial_cmp(&a.0).unwrap_or(std::cmp::Ordering::Equal));
    let pos = scored.iter().position(|(_, id)| *id == canonical_id)?;
    Some((pos + 1, scored.len()))
}

fn rank_bar_width(rank: Option<(usize, usize)>) -> f64 {
    match rank {
        Some((p, total)) if total > 0 => ((total - p + 1) as f64) / (total as f64) * 100.0,
        _ => 0.0,
    }
}

fn rank_text(rank: Option<(usize, usize)>) -> (String, &'static str) {
    match rank {
        Some((1, total)) => (format!("1 / {total}"), "exp-rank top"),
        Some((p, total)) => (format!("{p} / {total}"), "exp-rank"),
        None => (String::from("—"), "exp-rank"),
    }
}

fn render_group_table(scoreboard: &Scoreboard, model: &ipbr_core::ModelRecord) -> String {
    if model.groups.is_empty() {
        return r#"<div class="muted">no group scores</div>"#.to_string();
    }
    let mut html = String::from(r#"<div class="exp-table">"#);
    for (group, score) in &model.groups {
        let group_owned = group.clone();
        let rank = rank_for(scoreboard, &model.canonical_id, |m| {
            m.groups.get(&group_owned).copied()
        });
        let bar_width = rank_bar_width(rank);
        let (rank_label, rank_class) = rank_text(rank);
        html.push_str(&format!(
            r#"<span class="exp-label">{label}</span><span class="exp-bar"><span class="exp-bar-fill" style="width:{bar_width:.0}%"></span></span><span class="exp-value" data-tier="{tier}">{score:.1}</span><span class="{rank_class}">{rank_label}</span>"#,
            label = html_escape(group),
            tier = score_tier(*score),
        ));
    }
    html.push_str("</div>");
    html
}

fn render_metric_table(scoreboard: &Scoreboard, model: &ipbr_core::ModelRecord) -> String {
    if model.metrics.is_empty() {
        return r#"<div class="muted">no metrics</div>"#.to_string();
    }
    let mut html = String::from(r#"<div class="exp-table">"#);
    for (key, value) in &model.metrics {
        let key_owned = key.clone();
        let rank = rank_for(scoreboard, &model.canonical_id, |m| {
            m.metrics.get(&key_owned).copied()
        });
        let bar_width = rank_bar_width(rank);
        let (rank_label, rank_class) = rank_text(rank);
        html.push_str(&format!(
            r#"<span class="exp-label">{key}</span><span class="exp-bar"><span class="exp-bar-fill" style="width:{bar_width:.0}%"></span></span><span class="exp-value" data-tier="{tier}">{value:.1}</span><span class="{rank_class}">{rank_label}</span>"#,
            key = html_escape(key),
            tier = score_tier(*value),
        ));
    }
    html.push_str("</div>");
    html
}

fn render_source_pills(scoreboard: &Scoreboard, model: &ipbr_core::ModelRecord) -> String {
    if model.sources.is_empty() {
        return r#"<div class="muted">no sources</div>"#.to_string();
    }
    let mut html = String::new();
    for source in &model.sources {
        let status = scoreboard
            .source_summary
            .get(source)
            .map(|s| s.status.as_str())
            .unwrap_or("unknown");
        html.push_str(&format!(
            r#"<span class="pill" title="{status}">{name}</span>"#,
            name = html_escape(source),
            status = html_escape(status),
        ));
    }
    html
}

fn render_missing_pills(model: &ipbr_core::ModelRecord) -> String {
    if model.missing.metrics.is_empty() {
        return r#"<span class="muted">none</span>"#.to_string();
    }
    let mut html = String::new();
    for metric in &model.missing.metrics {
        html.push_str(&format!(
            r#"<span class="pill">{m}</span>"#,
            m = html_escape(metric),
        ));
    }
    html
}

const SCORING_PANEL: &str = r##"<details class="scoring" id="scoring">
<summary>how scoring works</summary>
<div class="scoring-body">
<p>Each model gets four role scores from public benchmarks. <strong>Idea</strong> measures open-ended creativity. <strong>Plan</strong> measures structured reasoning, function-calling, and multi-step decomposition. <strong>Build</strong> measures implementation skill — SWE-bench, LiveCodeBench, terminal tasks. <strong>Review</strong> measures preference judgment.</p>

<h3>scoring</h3>
<p>Each role score is the benchmark composite for that role, normalized to 0-100 and combined via weighted average of group scores. See the about page for the full math.</p>

<h3>missing data</h3>
<p>If a model is missing some metrics within a group, the group score blends from shrink-to-50 to trusting the present metrics across 60-80% group coverage. At 80% coverage and above, the present-weight mean is trusted directly.</p>

<p><a href="about.html">Full math, role definitions, and source list →</a></p>
</div>
</details>"##;
